version: '3.8'

services:
  db:
    image: 'docker-spring-boot-postgres:latest'
    restart: always
    container_name: a3_rota_menor_custo
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5434:5432
    volumes:
      - ./init.sh
